services:
  - type: web
    name: english-teacher-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 8000
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TAVUS_API_KEY
        sync: false
      - key: TAVUS_REPLICA_ID
        sync: false
      - key: TAVUS_PERSONA_ID
        sync: false